#ifndef AED_PROJ_2021_FLIGHT_H
#define AED_PROJ_2021_FLIGHT_H

class Flight;

#include "Airport.h"
#include "Cart.h"
#include "Luggage.h"
#include "Plane.h"
#include "Ticket.h"

#include <string>
#include <vector>

/**
 * @brief Represents a flight.
 */
class Flight {
private:
    /**
     * @brief This flight's index in the Company::_flights vector.
     */
    unsigned _id;

    /**
     * @brief This flight's number.
     */
    const unsigned _number;
    /**
     * @brief This flight's duration, in minutes.
     */
    unsigned _duration;
    /**
     * @brief All of this flight's tickets, bought or otherwise.
     */
    std::vector<Ticket *> _tickets;
    /**
     * @brief This flight's storage.
     */
    std::vector<Luggage *> _storage;
    /**
     * @brief This flight's origin.
     */
    Airport *_origin;
    /**
     * @brief This flight's destination.
     */
    Airport *_destination;
    /**
     * @brief This flight's departure date.
     */
    std::string _departureDate;
    /**
     * @brief This flight's plane.
     */
    Plane *_plane = nullptr;
    /**
     * @brief The cart associated with this flight.
     */
    Cart *_cart = nullptr;

    /**
     * @brief Generates a ticket for each seat on this plane.
     *
     * @details The tickets are generated by concatenating each row's letter
     *          with each column's number, padded with 0s, so that every seat
     *          has the same length.
     *
     * @details For example, if the plane has 2 rows and 10 columns, the
     *          generated tickets will have the values
     *          `"A01","A02",...,"A10","B01",...,"B10"`.
     *
     * @details This is advantageous, as it lets us use binary search to find a
     *          ticket by its seat.
     */
    void generateTickets();
    /**
     * @brief Deletes all tickets.
     */
    void deleteTickets();

public:
    /**
     * @brief Creates a new flight.
     *
     * @note Don't call this directly, use Company::createFlight.
     *
     * @param id The flight's index in the Company::_flights vector.
     * @param number The flight number.
     * @param duration The flight's duration, in minutes.
     * @param origin The flight's origin.
     * @param dest The flights's destination.
     * @param departureDate The flight's departure date.
     * @param plane The flight's plane.
     */
    Flight(unsigned id, unsigned number, unsigned duration, Airport *origin,
           Airport *dest, std::string departureDate, Plane *plane);
    ~Flight();

    // Getters
    /**
     * @return This flight's index in the Company::_flights vector.
     */
    unsigned getID() const { return _id; };
    /**
     * @return This flight's number.
     */
    unsigned getNumber() const { return _number; };
    /**
     * @return This flight's duration, in minutes.
     */
    unsigned getDuration() const { return _duration; };
    /**
     * @return This flight's departure date.
     */
    std::string getDepartureDate() const { return _departureDate; };
    /**
     * @return This flight's destination.
     */
    Airport *getDestination() const { return _destination; };
    /**
     * @return This flight's origin.
     */
    Airport *getOrigin() const { return _origin; };
    /**
     * @return This flight's plane.
     */
    Plane *getPlane() const { return _plane; };
    /**
     * @return The cart associated with this flight.
     */
    Cart *getCart() const { return _cart; };
    /**
     * @return All of this flight's tickets, bought or otherwise.
     */
    std::vector<Ticket *> getTickets() const { return _tickets; };
    /**
     * @return This flight's storage.
     */
    std::vector<Luggage *> getStorage() const { return _storage; };
    /**
     * @return How many tickets are available to buy.
     */
    unsigned getAvailability() const;

    // Setters
    /**
     * @brief Sets this flight's index in the Company::_flights vector.
     *
     * @param id The new index.
     */
    void setID(unsigned id) { _id = id; };
    /**
     * @brief Sets this flight's duration.
     *
     * @param duration The new duration.
     */
    void setDuration(unsigned duration) { _duration = duration; };
    /**
     * @brief Sets this flight's departure date.
     *
     * @param dep The new departure date.
     */
    void setDepartureDate(std::string dep) { _departureDate = dep; };
    /**
     * @brief Sets this flight's origin.
     *
     * @param origin The new origin.
     */
    void setOrigin(Airport *origin) { _origin = origin; };
    /**
     * @brief Sets this flight's destination.
     *
     * @param dest The new destination.
     */
    void setDestination(Airport *dest) { _destination = dest; };
    /**
     * @brief Sets this flight's plane.
     *
     * @param plane The new plane.
     */
    void setPlane(Plane *plane);

    /**
     * @brief Gets the ticket for the corresponding seat.
     *
     * @note Uses binary search, as the tickets are generated and stored in
     *       lexicographical order.
     *
     * @param seat The seat to search for.
     * @return A pointer to the ticket, if it was found, or nullptr otherwise.
     */
    Ticket *findTicketBySeat(const std::string &seat);

    /**
     * @brief Adds luggage to the plane's storage, associated to the flight.
     *
     * @param luggage The luggage to be added.
     */
    void addLuggage(Luggage *luggage) { _storage.push_back(luggage); };
};

#endif // AED_PROJ_2021_FLIGHT_H
